### ISSUE TITLE
1.5倍行距怎么理解？

### ISSUE THREAD

**Issue by krisfans** [BDZNH/XDUthesis-personal#2]
你好！本科论文的设计要求是文字的行间距为1.5倍，这个行间距是MS Word的1.5倍行距还是LaTeX的1.5倍行距？你在XDUthesis.cls里面是用setspace实现的，170行的位置
`\RequirePackage{setspace}
\if@WordOneHalf
  \setstretch{1.62}%设置Word下的行距1.5倍
\else
  \setstretch{1.5}%设置行距1.5倍
\fi`
但是这个宏包在texlive2019下利用`texdoc setspace`已经找不到了啊

**Comment by BDZNH** [comment]
@krisfans 论文格式内要求的1.5倍行距指的是word里面的，但是latex里面的1.5倍行距的实际值和word的不一致，在latex里面大概设置为1.62倍时与word的行距相近。    

textlive最好全安装，避免缺失包。如果已经确定宏包安装完全，需要贴一下具体的报错信息。

如果模板本身是编译出来的，那么你需要检查你写的文档内有没有格式错误。

**Comment by krisfans** [comment]
现在调整中文行距有一个专门的最新宏包，叫做`zhlineskip`，网址是[https://ctan.org/pkg/zhlineskip](https://ctan.org/pkg/zhlineskip ) ，`texlive2019`自带这个，它可以设置和`word`一样的文字行距而不改变脚注和公式的行距，楼主考虑试一下

**Comment by BDZNH** [comment]
@krisfans 现在我手里没有环境试验。如果你在使用模板发现有问题可以`fork`修改之后发起`pull request`。
不急的话我回深圳之后再看这个问题。

**Comment by BDZNH** [comment]
@krisfans 我用最新的textlive编译是没有问题的，没有仔细查这个包的情况。如果你编译有问题的话，更新textlive看看。
