### ISSUE TITLE
致谢的章标题还是会显示chapter怎么解决呢？

### ISSUE THREAD

**Issue by fancyteo** [BDZNH/XDUthesis-personal#7]
![image](https://user-images.githubusercontent.com/77785817/115832908-05636c80-a446-11eb-90de-f18fbf6b56cd.png)

**Comment by BDZNH** [comment]
@fancyteo  抱歉 github 没有提醒我有新的 issue ，我现在才看到，问一下这个问题现在是否解决了呢？

**Comment by fancyteo** [comment]
已经解决好了，之前好像有issue引到别的项目里面，大概就是给texlive的fancyhdr包里面补一个降级的V3.10的sty包就可以了U•ェ•*U

**Comment by BDZNH** [comment]
@fancyteo 搞定就好，这个仓库也是从另外一个学长那里 fork 过来的，我看到他那边有解法了。
